name: PHPStan

on:
  push:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    name: phpstan - Guzzle ${{ matrix.guzzle }}
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        guzzle: ['^7.3', '^8.0']
    steps:
      - uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install composer dependencies
        run: composer update --with="guzzlehttp/guzzle:${{ matrix.guzzle }}" --no-interaction --prefer-dist

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github
